### ISSUE TITLE
DockerException when running inside Databricks ManageMLFlow cluster

### ISSUE THREAD

**Issue by mchrestkha** [Ark-kun/google_cloud_mlflow#2]
- Cluster: 9.0 ML (Spark 3.1.2, Scala 2.12)
- GCP Service Account has proper permissions
- Client successful set via ```client=mlflow.deployments.get_deploy_client("google_cloud")```
- Model successfully trained and model registered using tutorial here https://docs.databricks.com/applications/mlflow/quick-start-python.html#automatically-log-training-runs-to-mlflow

Error on  this command
``` 
deployment = client.create_deployment(
    name="mlflow_on_gcp",
    model_uri=model_uri) 
```

Error Details

```
INFO:google_cloud_mlflow._mlflow_model_gcp_deployment_utils:Project not set. Using <project> as project
INFO:google_cloud_mlflow._mlflow_model_gcp_deployment_utils:Destination image URI not set. Building and uploading image to gcr.io/<project/image>
INFO:google_cloud_mlflow._mlflow_model_gcp_deployment_utils:Building image
2021/08/31 03:57:03 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/08/31 03:57:05 INFO mlflow.models.docker_utils: Building docker image with name gcr.io/<project/image>
DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) ```

**Comment by Ark-kun** [comment]
Can you please provide the output from `docker version`?

Also `curl -s --unix-socket /var/run/docker.sock  http://localhost/version`

**Comment by Ark-kun** [comment]
Version 0.0.4 no longer requires Docker to be installed.

P.S. It does **not** require Google Cloud SDK or `gcloud` either.
