### ISSUE TITLE
_build_serving_image doesn't actually pushes the built image

### ISSUE THREAD

**Issue by imrehg** [Ark-kun/google_cloud_mlflow#3]
While reading the source of this project, came across this block of code in the `_build_serving_image` function. Due to that `return` in the first line of the quoted segment, the rest of the code (that should do the pushing the image to the registry) is unreachable. I presume it's not intended?

https://github.com/Ark-kun/google_cloud_mlflow/blob/014e3ba09708ef4b33036dd92402d932041e40c6/google_cloud_mlflow/_mlflow_model_gcp_deployment_utils.py#L207-L222

**Comment by Ark-kun** [comment]
Thank you for reporting this issue.
This dead code was removed on Jan 7 in https://github.com/Ark-kun/google_cloud_mlflow/commit/52ebf42a2ed7d60979ea55152a9e88496155edc8

The image is being pushed to the repository by the preceding code.

If you're interested, here is how the code progressed:

1. Use MLflow's build process that uses `docker` CLI
2. Use `docker` Python library to push the image
3. Patch MLflow to build and push image using Cloud Build `gcloud` CLI
4. Patch MLflow to build and push image using Cloud Build client library
5. [prerelease] Use Vertex AI's built-in serving images

**Comment by Ark-kun** [comment]
Please report any other issues you've found.
